name: parknwash
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: 
  flutter_svg: 
  get: 
  shared_preferences: ^2.2.3
  get_storage:
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  awesome_snackbar_content:
  google_sign_in: ^6.2.1
  intl:
  connectivity_plus:
  flutter_share: ^2.0.0
  pretty_qr_code: ^3.3.0
  loading_animation_widget: ^1.2.1
  awesome_notifications: ^0.9.3+1
  flutter_app_badger: ^1.5.0
  google_maps_flutter: ^2.7.0
  permission_handler: ^11.3.1
  # geolocator: ^12.0.0
  location: ^7.0.0
  latlong2: ^0.9.1
  geoflutterfire2: ^2.3.15

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/
    - assets/anims/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
    - family: Kalam
      fonts:
        - asset: assets/fonts/Kalam/Kalam-Regular.ttf
